baseURL = "/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "Healing Garden"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "blog"
name = "Blog"
weight = ""
[[menu.desktop]]
URL = "resource"
name = "Resources"
weight = ""
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "astro"
description = "A digital garden on collective healing, mental health, intersectional healing, and reflections. By the community, for the community"
mainSections = ["content"]
[params.banner]
heading = "Community-centric help by the community, for the community"
image = ""
[params.blog]
heading = "Hi! I believe that while healing can be done alone, peer support is super helpful."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
enable = false
title = "Contact us for more information."
[params.footer]
address = ""
content = "Healing doesn't have to be a lonely process; I think healthcare should be affordable and accessible to everyone. No more paywalled content, no more over-emphasis on discriminatory and ableist clinicians. It's time for survivor-centric, survivor-led healing. "
copyright = ""
hours = ""
title = "About This Site"
[params.gallery]
enable = false
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = ""
facebook = ""
instagram = ""
linkedin = ""
twitter = ""
yelp = ""
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
  
